/// Flutter icons Home
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Home
///      fonts:
///       - asset: fonts/Home.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter_web/widgets.dart';

class Home {
  Home._();

  static const _kFontFam = 'Home';

  static const IconData github_circled =
      IconData(0xf09b, fontFamily: _kFontFam);
}
